Create tally
AndrewIndeche/Learning-Project pull request #29
Opened 2022-11-16 12:25 UTC by AndrewIMLEx

This branch:
[This branch: -creates a new component and page called tally. 
-Adds styling to the tally.

2022-11-16 12:42 UTC, AndrewIMLEx commented
Good day @ML-ex , I have made changes to the branch names and descriptions created pull requests. Also if you have time, could I kindly request for a review of the code used in styling and JSX part of the homepage?

2022-11-30 12:20 UTC, ML-ex requested changes
- Branch on local is still not following best practices for branch naming... I see the branch name as "create-Game-tally"... Please revisit all the link resources I have shared with you previously on best practices.

- The fields in the Game Tally segment are input fields, will the users be populating those fields manually or what's the thought process behind this?

- Your User Interface has deviated from the designs you created here and that we approved... ==> https://github.com/AndrewIMLEx/Learning-Project/blob/rebuilding-history/designs/Non%20Logged%20In%20Gameplay.png  why is that?  The product should stay true to approved designs... Please make the relevant changes.

2022-11-30 13:42 UTC, AndrewIMLEx commented
> * Branch on local is still not following best practices for branch naming... I see the branch name as "create-Game-tally"... Please revisit all the link resources I have shared with you previously on best practices.
> * The fields in the Game Tally segment are input fields, will the users be populating those fields manually or what's the thought process behind this?
> * Your User Interface has deviated from the designs you created here and that we approved... ==> https://github.com/AndrewIMLEx/Learning-Project/blob/rebuilding-history/designs/Non%20Logged%20In%20Gameplay.png  why is that?  The product should stay true to approved designs... Please make the relevant changes.

@ML-ex I created a new branch called create-tally since the create-Game-tally branch had already been merged with the rebuilding history branch, I will work on the output fields and the design

2023-01-24 09:30 UTC, ML-ex approved these changes

2023-01-24 10:19 UTC, merged